pipeline {
    agent any
    stages {
        stage('Initialize Git POLL SCM Feature') {
            steps {
                //enable remote triggers
                script {
                    properties([[$class: 'GithubProjectProperty', displayName: '', projectUrlStr: 'https://github.com/bipin115/PG_DevOps_SimpliLearn_Projects.git/'], pipelineTriggers([pollSCM('* * * * *')])])
                }
                
            }
        }
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Docker Build and Tag') {
           steps {
              
                sh 'docker build -t samplewebapp:latest -f "./DockerDeployWebapp.txt" .' 
		   
                sh 'docker tag samplewebapp bipin115/samplewebapp:latest'       
          }
        }
        
        stage('Publish image to Docker Hub') {
            
            steps {
                    withDockerRegistry([ credentialsId: "dockerHub", url: "" ]) {
                    sh  'docker push bipin115/samplewebapp:lates'
                    } 
            }
        }
     
      stage('Run Docker container on Jenkins Agent') {
             
            steps 
			{
                sh "docker run -d -p 9090:8080 bipin115/samplewebapp"
 
            }
        }
        
       stage('Run Docker container on remote hosts') {
             
            steps {
                sh "docker -H ssh://jenkins@3.6.37.189 run -d -p 8003:8080 bipin115/samplewebapp"
 
            }
        }
    }
}
